### ISSUE TITLE
Feasivbility to use ollama to reduce cost? 

### ISSUE THREAD

**Issue by dgoryeo** [dtinth/autosub#1]
Thanks for this very promising work.

I was wondering if it would be feasivbile to use any of ollama models to reduce cost?

**Comment by dtinth** [comment]
@dgoryeo Unfortunately, I haven’t tried it. The last time I tested Ollama, it did not perform well on Thai text. Therefore, I doubt that I will be able to achieve a **less than 1% WER**, although I might be wrong.

But it might work well enough for your particular use case which may be different than mine. For that, please feel free to use the code in this repo to help you conduct your own experiments.
